name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t jimakosak/webserver .

      - name: Log in to Docker Registry
        run: echo "$DOCKER_REGISTRY_USERNAME" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin
        env:
          DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Tag Docker image
        run: docker tag jimakosak/webserver jimakosak/webserver:${{ github.sha }}

      - name: Push Docker image
        run: docker push jimakosak/webserver:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy application
        run: echo "Deploy your application here"
